### ISSUE TITLE
Track topic does not contain big orange cones

### ISSUE THREAD

**Issue by wouter-heerwegh** [FS-Driverless/Formula-Student-Driverless-Simulator#254]
I was playing around with the testing_only topics to measure how well our system is performing but I found that in the `/fsds/testing_only/track` topic no big orange cones are given, even though they are present.

This was tested on the first test map. I'll look into the `airsim_ros_wrapper` to update this issue

**Comment by davidoort** [comment]
This is not an issue in the ROS wrapper but in one of the blueprints of unreal engine which only stores cones on the yellow and blue cone splines.
