### ISSUE TITLE
Testing only topics reliability

### ISSUE THREAD

**Issue by manderino1** [FS-Driverless/Formula-Student-Driverless-Simulator#256]
I'm trying to use the fsds/testing_only/cones and odom topics to test the precision of my calculated cone poses but, when I plot them in rviz, I find them shifted like map was shifted down with respect to the odometry.
Is this a problem into the sim or something wrong by me while plotting them? Thank you!
(For reference, to get a correct map i have in the training map to shift down x axis, I know that they are with respect to the starting position, but the starting position in /fsds/testing_only/odom is about 0 on the x axis)

![Schermata da 2020-11-25 17-16-42](https://user-images.githubusercontent.com/44238126/100256890-9bea3b00-2f45-11eb-867f-7180d9900287.png)
![Schermata da 2020-11-25 17-18-34](https://user-images.githubusercontent.com/44238126/100256898-9d1b6800-2f45-11eb-85fc-fb394c3ffccd.png)

**Comment by SijmenHuizenga** [comment]
@davidoort any idea what's going on here?

**Comment by davidoort** [comment]
This is the famous x-offset issue that we struggled with for a while (the one that made the car drive through cones when it thought it was following the midline). I seem to remember that this was fixed at the competition, so not sure why this is popping up again. @manderino1 could you test this without any changes in the ros wrapper for different maps and see if you get the same issue?

**Comment by manderino1** [comment]
@davidoort I tried also other mapsbut it seems to be on every one shifted about 2 metres on the x-axis
If I edit my plotting node with (x = x-2) it's almost perfect, but if I simply plot the topic it's clearly shifted.

**Comment by davidoort** [comment]
Okay, we can always include this offset in the wrapper as a quick fix, but it is not very elegant. @SijmenHuizenga I believe this was something related to the cg definition of the car in Unreal. If we could fix this offset in the blueprint that loads this initial position I think it would be better

**Comment by wouter-heerwegh** [comment]
Does this onoy happen in a specifc case or version? I've been using the testing topics for a couple of months and have not seen this before.

**Comment by ckurtz22** [comment]
I would expect that this is some sort of reference frame issue.

**Comment by ckurtz22** [comment]
> This is the famous x-offset issue that we struggled with for a while (the one that made the car drive through cones when it thought it was following the midline). I seem to remember that this was fixed at the competition, so not sure why this is popping up again. @manderino1 could you test this without any changes in the ros wrapper for different maps and see if you get the same issue?

Looks like the relevant issue being referred to here is #144

**Comment by MarvinKlemp** [comment]
I can confirm that I also encountered this issue. Subtracted x-2 for all initial cone positions fix this.
