### ISSUE TITLE
ROS_Bridge issues

### ISSUE THREAD

**Issue by kopebryant** [FS-Driverless/Formula-Student-Driverless-Simulator#276]
Hi.
I installed the latest version of the simulation on my windows pc and the rosbridge on my ubuntu laptop. When the system sends commands like throttle=0.2 the simulation always goes full throttle. I don't have this problem if everything is installed on the same ubuntu pc. Does anybody knows what causes this issue?
I also have a problem with the ROS odometry topic. I know that there are older threads regarding this topic but I still wanted to know if anyone has updates or figured this out. When the simulations runs a few minutes and I reset the car to the starting position, the updated position is displayed on the odometry-ROS-topic up to 30 secs later.

**Comment by wouter-heerwegh** [comment]
Hi @kopebryant 

I've run the same settings as you on Ubuntu 18.04 with ROS Melodic and I can't replicate your problem.

**Comment by kopebryant** [comment]
The Problem is definitely my algorithm. It seems that it buffers old data and doesn't use the new car position. If nothing runs in the background than the car position refreshes immediately in the rostopic. 
Thank you very much for your help and patience.

**Comment by wouter-heerwegh** [comment]
Hi @kopebryant 

Great that you were able to find the problem. If you keep processing old data, you could try to make the queue size of the subscriber, that is handling the position of the car, smaller (for instance 1).

Hope that helps!
