### ISSUE TITLE
Testing only odometry messages contain wrong data

### ISSUE THREAD

**Issue by mateusz-lichota** [FS-Driverless/Formula-Student-Driverless-Simulator#283]
[The definition of the Odometry message](http://docs.ros.org/en/noetic/api/nav_msgs/html/msg/Odometry.html) message says "The twist in this message should be specified in the coordinate frame given by the child_frame_id". However, the testing only Odometry message that the fsds_ros2_bridge (and probably also fsds_ros_bridge) publishes contains both pose and twist in the map frame, which causes errors when processing that data with applications assuming adherence to the standard (like robot_localization).  I'm changing this behavior in my fork; let me know if you'd like a pull request with the changes to this repo.

**Comment by wouter-heerwegh** [comment]
It would be nice to have these changes indeed. I think the behaviour of the GSS is wrong aswell, as it is also showing the speed of the car in the map frame. We'll port the changes also to ros 1 and the GSS
