### ISSUE TITLE
UE4 can't compile V2.1.0

### ISSUE THREAD

**Issue by MattBrth** [FS-Driverless/Formula-Student-Driverless-Simulator#285]
When i try to rebuild Blocks and AirSim through UE4 just after runing build.cmd in the AirSim folder I get this issue : 
FSOnline could not be compiled. Try rebuilding from source manually.

This is the log associated : 

How can I fix this ? Thank you !

------------------------------------------------------------------------------------------------------------------

Log file open, 03/03/22 02:37:50
LogWindows: Failed to load 'aqProf.dll' (GetLastError=126)
LogWindows: File 'aqProf.dll' does not exist
LogWindows: Failed to load 'VtuneApi.dll' (GetLastError=126)
LogWindows: File 'VtuneApi.dll' does not exist
LogWindows: Failed to load 'VtuneApi32e.dll' (GetLastError=126)
LogWindows: File 'VtuneApi32e.dll' does not exist
LogConsoleResponse: Display: Failed to find resolution value strings in scalability ini. Falling back to default.
LogConsoleResponse: Display: Failed to find resolution value strings in scalability ini. Falling back to default.
LogInit: Display: Running engine for game: FSOnline
LogPlatformFile: Not using cached read wrapper
LogTaskGraph: Started task graph with 5 named threads and 59 total threads with 3 sets of task threads.
LogStats: Stats thread started at 0.201491
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +1:00, Platform Override: ''
LogInit: Display: Loading text-based GConfig....
LogPluginManager: Mounting plugin MeshPainting
LogPluginManager: Mounting plugin XGEController
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin LiveLink
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin EnvironmentQueryEditor
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting plugin CLionSourceCodeAccess
LogPluginManager: Mounting plugin GitSourceControl
LogPluginManager: Mounting plugin AnimationSharing
LogPluginManager: Mounting plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting plugin PerforceSourceControl
LogPluginManager: Mounting plugin PixWinPlugin
LogPluginManager: Mounting plugin PluginUtils
LogPluginManager: Mounting plugin PropertyAccessNode
LogPluginManager: Mounting plugin NullSourceCodeAccess
LogPluginManager: Mounting plugin SubversionSourceControl
LogPluginManager: Mounting plugin TextureFormatOodle
LogPluginManager: Mounting plugin PlasticSourceControl
LogPluginManager: Mounting plugin RiderSourceCodeAccess
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin XCodeSourceCodeAccess
LogPluginManager: Mounting plugin OodleData
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin AutomationUtils
LogPluginManager: Mounting plugin OodleNetwork
LogPluginManager: Mounting plugin ChaosClothEditor
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin ChaosCloth
LogPluginManager: Mounting plugin ChaosEditor
LogPluginManager: Mounting plugin ChaosSolverPlugin
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin GeometryCollectionPlugin
LogPluginManager: Mounting plugin GeometryProcessing
LogPluginManager: Mounting plugin MagicLeap
LogPluginManager: Mounting plugin ChaosNiagara
LogPluginManager: Mounting plugin Niagara
LogPluginManager: Mounting plugin MagicLeapLightEstimation
LogPluginManager: Mounting plugin LuminPlatformFeatures
LogPluginManager: Mounting plugin OpenImageDenoise
LogPluginManager: Mounting plugin MagicLeapPassableWorld
LogPluginManager: Mounting plugin MotoSynth
LogPluginManager: Mounting plugin PlanarCut
LogPluginManager: Mounting plugin MagicLeapMedia
LogPluginManager: Mounting plugin ProxyLODPlugin
LogPluginManager: Mounting plugin MLSDK
LogPluginManager: Mounting plugin AndroidMedia
LogPluginManager: Mounting plugin PlatformCrypto
LogPluginManager: Mounting plugin PythonScriptPlugin
LogPluginManager: Mounting plugin AvfMedia
LogPluginManager: Mounting plugin SkeletalReduction
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin MediaPlayerEditor
LogPluginManager: Mounting plugin WebMMedia
LogPluginManager: Mounting plugin WmfMedia
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin AndroidMoviePlayer
LogPluginManager: Mounting plugin TemplateSequence
LogPluginManager: Mounting plugin AndroidPermission
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin AppleMoviePlayer
LogPluginManager: Mounting plugin AssetTags
LogPluginManager: Mounting plugin ArchVisCharacter
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin ChunkDownloader
LogPluginManager: Mounting plugin AudioSynesthesia
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin GooglePAD
LogPluginManager: Mounting plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting plugin IOSDeviceProfileSelector
LogPluginManager: Mounting plugin GoogleCloudMessaging
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin LocationServicesBPLibrary
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin MobilePatchingUtils
LogPluginManager: Mounting plugin OpenXR
LogPluginManager: Mounting plugin OpenXREyeTracker
LogPluginManager: Mounting plugin OpenXRHandTracking
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin ScreenshotTools
LogPluginManager: Mounting plugin PostSplashScreen
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin PropertyAccessEditor
LogPluginManager: Mounting plugin SignificanceManager
LogPluginManager: Mounting plugin SoundFields
LogPluginManager: Mounting plugin WebMMoviePlayer
LogPluginManager: Mounting plugin WindowsMoviePlayer
LogPluginManager: Mounting plugin Synthesis
LogPluginManager: Mounting plugin Takes
LogPluginManager: Mounting plugin CameraShakePreviewer
LogPluginManager: Mounting plugin GameplayCameras
LogPluginManager: Mounting plugin DataValidation
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin GameplayTagsEditor
LogPluginManager: Mounting plugin GeometryMode
LogPluginManager: Mounting plugin MacGraphicsSwitching
LogPluginManager: Mounting plugin CurveEditorTools
LogPluginManager: Mounting plugin CryptoKeys
LogPluginManager: Mounting plugin MaterialAnalyzer
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin MobileLauncherProfileWizard
LogPluginManager: Mounting plugin PluginBrowser
LogPluginManager: Mounting plugin OnlineSubsystemIOS
LogPluginManager: Mounting plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting plugin ContentBrowserClassDataSource
LogPluginManager: Mounting plugin ContentBrowserFileDataSource
LogPluginManager: Mounting plugin ContentBrowserAssetDataSource
LogPluginManager: Mounting plugin AirSim
LogInit: Warning: Incompatible or missing module: Blocks
LogInit: Warning: Incompatible or missing module: AirSim
Running E:/Games/UE_4.27/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="C:/Users/berth/Formula-Student-Driverless-Simulator/UE4Project/FSOnline.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
@progress push 5%
@progress pop
Building BlocksEditor...
Using Visual Studio 2019 14.29.30140 toolchain (C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133) and Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 2 actions with 20 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 50%
  [1/2] UE4Editor-AirSim.dll
     Cr?ation de la biblioth?que C:\Users\berth\Formula-Student-Driverless-Simulator\UE4Project\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\Development\AirSim\UE4Editor-AirSim.suppressed.lib et de l'objet C:\Users\berth\Formula-Student-Driverless-Simulator\UE4Project\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\Development\AirSim\UE4Editor-AirSim.suppressed.exp
  Module.AirSim.cpp.obj : error LNK2019: symbole externe non r?solu "__declspec(dllimport) private: static class UClass * __cdecl UPhysicalMaterial::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UPhysicalMaterial@@CAPEAVUClass@@XZ) r?f?renc? dans la fonction "public: __cdecl ACarPawn::ACarPawn(void)" (??0ACarPawn@@QEAA@XZ)
    Conseil sur les symboles d?finis et susceptibles de correspondre?:
      "__declspec(dllimport) private: static class UClass * __cdecl AActor::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@AActor@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl ADirectionalLight::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@ADirectionalLight@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl ALandscapeProxy::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@ALandscapeProxy@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl APawn::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@APawn@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl AWorldSettings::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@AWorldSettings@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UActorComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UActorComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UBlendableInterface::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UBlendableInterface@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UBlueprintFunctionLibrary::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UBlueprintFunctionLibrary@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UCameraComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UCameraComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UChildActorComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UChildActorComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UMaterial::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UMaterial@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UMaterialParameterCollection::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UMaterialParameterCollection@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UMeshComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UMeshComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UObject::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UObject@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UPrimitiveComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UPrimitiveComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl URotatingMovementComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@URotatingMovementComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl USceneCaptureComponent2D::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@USceneCaptureComponent2D@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl USceneComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@USceneComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl USkinnedMeshComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@USkinnedMeshComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl USpringArmComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@USpringArmComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UStaticMeshComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UStaticMeshComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UTextRenderComponent::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UTextRenderComponent@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UTextureRenderTarget2D::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UTextureRenderTarget2D@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UTireConfig::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UTireConfig@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UUserWidget::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UUserWidget@@CAPEAVUClass@@XZ)
      "__declspec(dllimport) private: static class UClass * __cdecl UWheeledVehicleMovementComponent4W::GetPrivateStaticClass(void)" (__imp_?GetPrivateStaticClass@UWheeledVehicleMovementComponent4W@@CAPEAVUClass@@XZ)
  C:\Users\berth\Formula-Student-Driverless-Simulator\UE4Project\Plugins\AirSim\Binaries\Win64\UE4Editor-AirSim.dll : fatal error LNK1120: 1 externes non r?solus
LogInit: Warning: Still incompatible or missing module: Blocks
LogInit: Warning: Still incompatible or missing module: AirSim
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (48)
LogModuleManager: Shutting down and abandoning module PythonScriptPluginPreload (46)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL (44)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes (42)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (40)
LogModuleManager: Shutting down and abandoning module OodleDataCompressionFormat (38)
LogModuleManager: Shutting down and abandoning module XGEController (36)
LogXGEController: Cannot use XGE Controller as Incredibuild is not installed on this machine.
LogXGEController: Cleaning working directory: C:/Users/berth/AppData/Local/Temp/UnrealXGEWorkingDir/
LogModuleManager: Shutting down and abandoning module AnimationModifiers (34)
LogModuleManager: Shutting down and abandoning module AudioEditor (32)
LogModuleManager: Shutting down and abandoning module PropertyEditor (31)
LogModuleManager: Shutting down and abandoning module TextureCompressor (28)
LogModuleManager: Shutting down and abandoning module RenderCore (26)
LogModuleManager: Shutting down and abandoning module Landscape (24)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
Log file closed, 03/03/22 02:37:57

**Comment by loremacchia** [comment]
Were you able to solve this? I'm having the same problem

**Comment by MattBrth** [comment]
I unfortunately did not. Just clone the Master branch and don't forget to git lfs pull after. It should work.
