### ISSUE TITLE
Automating tests on release version

### ISSUE THREAD

**Issue by loremacchia** [FS-Driverless/Formula-Student-Driverless-Simulator#288]
Hi, we're using the release version of FSDS to test our driverless system. We'd like to automate testing and to do that we'd need a way to select a course from the FSDS.sh script or the command line in general. Is there a way to do that?

**Comment by wouter-heerwegh** [comment]
Not that I know of, you could maybe run a script to always click in a specific position. Or maybe in the homescreen you could add keybindings to the selector and the start simulator button.
