### ISSUE TITLE
Lidar does not contain points if `VerticalFOVUpper= 0`

### ISSUE THREAD

**Issue by wouter-heerwegh** [FS-Driverless/Formula-Student-Driverless-Simulator#318]
When setting this value to 0, basically setting the lidar to horizon mode, the pointclouds published will be 0. Using debugpoints shows that none are drawn.

**Comment by b1n-ch1kn** [comment]
I think i've always been able to get a single laser working with 0 upper, 0 lower FOV. 
This is screenshot was from the bridge running on `master`.
![image](https://user-images.githubusercontent.com/77331735/188403888-1aaa3dc8-3963-428f-a92f-0391e6a7c716.png)
Here are my settings:
![image](https://user-images.githubusercontent.com/77331735/188404008-492437fe-21de-4d96-873c-8872bcce102f.png)

**Comment by wouter-heerwegh** [comment]
To be more specific, the settings I used were:
```
"Lidar1": {
	"SensorType": 6,
	"Enabled": true,
	"X": 0.45,
	"Y": 0,
	"Z": 0.55,
	"Roll": 0,
	"Pitch": 0,
	"Yaw": 0,
	"NumberOfLasers": 4,
	"PointsPerScan": 4096,
	"VerticalFOVUpper": 0,
	"VerticalFOVLower": -5,
	"HorizontalFOVStart": -90,
	"HorizontalFOVEnd": 90,
	"RotationsPerSecond": 10,
	"DrawDebugPoints": false
}
```

This gave me the following message
![image](https://user-images.githubusercontent.com/20578313/188479417-ef3144db-3656-4de4-af19-554bc0dfe5ad.png)
I checked with drawdebugpoints and it doesn't seem like any line traces are being cast

**Comment by wouter-heerwegh** [comment]
Rotations seem to be incorrect. Empty pointcloud appears if no object is hit.
