### ISSUE TITLE
Unable to change camera Image Type

### ISSUE THREAD

**Issue by Lamfurst** [FS-Driverless/Formula-Student-Driverless-Simulator#354]
Hey guys! 
I Install the fsds from release binaries, and I change the settings.json as following.
![image](https://user-images.githubusercontent.com/66519297/220538702-e19efd46-83d1-4581-8f13-3b1279fa9492.png)

Seems that the position change works but ImageType does not. I wrote a simple subscriber to catch the information in /fsds/cam2 topic using the following code as following:
![image](https://user-images.githubusercontent.com/66519297/220539106-884e6cd0-69cb-4d5c-a50e-cf9c37323509.png)
But the ROS_INFO gives these information which mismatches with the settings.json (both height, width and encoding type).
![image](https://user-images.githubusercontent.com/66519297/220539327-461996eb-5c42-4bcd-aeb9-e4b9b5aed954.png)

I am new to ROS and I'd much appreciate it if you could tell me how should I deal with this problem. 
Also, please tell me if there is a better way to write a subscriber function that catches the msg only once. Thx!

**Comment by masskro0** [comment]
Did you restart the simulator? I usually restart it after every change in the settings.json file (not sure if this is necessary, but it works).

**Comment by Lamfurst** [comment]
Thanks for your response. I realized that this is because I did not change the settings.json on both sides
