### ISSUE TITLE
Packaging from windows to ubuntu does not work

### ISSUE THREAD

**Issue by RafaGuil** [FS-Driverless/Formula-Student-Driverless-Simulator#369]
Hi. I've packaged the simulator for Windows and I didn't have any problem. But when I packaged it for Linux I haved this error:
UATHelper: Empaquetado (Linux): ********** BUILD COMMAND STARTED **********
UATHelper: Empaquetado (Linux): Running: C:\Users\Rafa Guil Valero\UE_4.27\Engine\Binaries\DotNET\UnrealBuildTool.exe Blocks Linux Development -Project="C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\FSOnline.uproject"  "C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\FSOnline.uproject" -NoUBTMakefiles  -r
emoteini="C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project" -skipdeploy -distribution -Manifest="C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\Intermediate\Build\Manifest.xml" -NoHotReload -log="C:\Users\Rafa Guil Valero\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Users+Rafa+Guil+Valero+UE_4.27\UBT
-Blocks-Linux-Development.txt"
UATHelper: Empaquetado (Linux):   Using 'git status' to determine working set for adaptive non-unity build (C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator).
UATHelper: Empaquetado (Linux):   WARNING: Library 'C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\Plugins\AirSim\Source\AirLib\deps\rpclib\lib\librpc.a' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for i
t. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
LogSlate: Took 0.000112 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/DroidSansMono.ttf' (77K)
UATHelper: Empaquetado (Linux):   Waiting for 'git status' command to complete
UATHelper: Empaquetado (Linux):   ------- Build details --------
UATHelper: Empaquetado (Linux):   Using toolchain located at 'C:/UnrealToolchains/v19_clang-11.0.1-centos7/x86_64-unknown-linux-gnu'.
UATHelper: Empaquetado (Linux):   Using clang (C:/UnrealToolchains/v19_clang-11.0.1-centos7/x86_64-unknown-linux-gnu\bin\clang++.exe) version '11.0.1' (string), 11 (major), 0 (minor), 1 (patch)
UATHelper: Empaquetado (Linux):   Using bundled libc++ standard C++ library.
UATHelper: Empaquetado (Linux):   Using lld linker
UATHelper: Empaquetado (Linux):   Using llvm-ar : C:/UnrealToolchains/v19_clang-11.0.1-centos7/x86_64-unknown-linux-gnu\bin/llvm-ar.exe
UATHelper: Empaquetado (Linux):   Using old way to relink circularly dependent libraries (with a FixDeps step).
UATHelper: Empaquetado (Linux):   ------------------------------
UATHelper: Empaquetado (Linux):   Writing manifest to C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\Intermediate\Build\Manifest.xml
UATHelper: Empaquetado (Linux):   Building Blocks...
UATHelper: Empaquetado (Linux):   Building 2 actions with 20 processes...
UATHelper: Empaquetado (Linux):     [1/2] Blocks
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     ld.lld: error: cannot open C:/Users/Rafa Guil Valero/Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: no such file or directory
UATHelper: Empaquetado (Linux):     clang++: error: linker command failed with exit code 1 (use -v to see invocation)
UATHelper: Empaquetado (Linux):     Failed to link C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\Binaries\Linux\Blocks after 10 retries
UATHelper: Empaquetado (Linux): Took 3,7330101s to run UnrealBuildTool.exe, ExitCode=6
UATHelper: Empaquetado (Linux): UnrealBuildTool failed. See log for more details. (C:\Users\Rafa Guil Valero\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Users+Rafa+Guil+Valero+UE_4.27\UBT-Blocks-Linux-Development.txt)
UATHelper: Empaquetado (Linux): AutomationTool exiting with ExitCode=6 (6)
UATHelper: Empaquetado (Linux): BUILD FAILED
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/4c6f5445-4f5b-4c90-b90a-82fff0292024)

What can I do?

**Comment by RafaGuil** [comment]
The file is not there. 
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/c3991bdb-71ae-458c-96f7-2b1bfa8588da)

**Comment by wouter-heerwegh** [comment]
Hi @RafaGuil 

The library should be present in `external\rpclib\build\Debug` could you temporarily copy is from here to `Formula-Student-Driverless-Simulator/UE4Project/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a`.

I think I will have to modify the build.cmd script from AirSim

**Comment by RafaGuil** [comment]
I can't find librpc.a in `C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\AirSim\external\rpclib\build\Debug`.
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/e5b831fc-c86f-4540-928a-97734cf62f05)

In fact, there is no file called `librpc.a` in the entire repository:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/18335cc0-0e85-4d1c-8711-f65d8079bdfd)

**Comment by wouter-heerwegh** [comment]
You have built AirSim, right? Because it should be built for AirSim.

**Comment by RafaGuil** [comment]
Yes, I rebuilt it and it still doesn't work. 
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/ca24757f-4bec-464d-84bd-d7cfef6b0b0e)

That's what build.cmd says:
[building.txt](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/files/15282469/building.txt)

**Comment by wouter-heerwegh** [comment]
Hi @RafaGuil,

I just compiled for Windows without issue (Windows 11, Visual Studio v2019, Unreal Engine 4.27.2). It seems that the rpc library is built in Windows as `rpc.lib`.

Are you building for Windows aswell? Or for Linux?

**Comment by RafaGuil** [comment]
I'm building for Linux. I have no problem for Windows.

**Comment by wouter-heerwegh** [comment]
Unreal Engine seems to try to rebuild the AirSim plugin, and is trying to find `librpc.a`

If you want a quick and dirty solution, you could compile in WSL or on your linux system and copy the needed library files over. Important to note is that you will have to change the used clang version from v12 to v8, in order to build `librpc.a` without the  `pthread_cond_clockwait` symbol.

I quickly used WSL (Ubuntu 20.04), compiled AirSim, then opened the Unreal Editor, rebuild the plugin, and packaged for Linux succesfully.

I know that this is a terrible workflow, but I'll need some time to look into this. Feel free to let me know if you struggle with something.

**Comment by RafaGuil** [comment]
I've copy `librpc.a` in `C:\Users\Rafa Guil Valero\Formula-Student-Driverless-Simulator\UE4Project\Plugins\AirSim\Source\AirLib\deps\rpclib\lib` from my Ubuntu 20.04 builded repo, and I have this error with -v19 clang-11.0.1-based:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/1a9b4d0f-dc35-41f6-8ceb-465c284137cb)
then I tried with -v15 clang-8.0.1-based and it fails again:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/d392891a-686f-4234-9a37-80da3e3a0609)
Finally I tried again with -v8 clang-3.9.0-based In case I had misunderstood you, but it still fails.
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/65438d6a-26c2-466b-8ed3-1a481212d518)

I also tried to compile setup.sh and build.sh with clang8 on WSL (Ubuntu 20.04), but build.sh fails:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/4e0b9490-c23c-4ff9-ab67-499092855937)

**Comment by wouter-heerwegh** [comment]
Hi @RafaGuil,

Unreal Engine is complaining about the `pthread_cond_clockwait` symbol, so the library was probably not rebuild after changing both the setup and build script to use clang-8. It's best to remove the build_debug folder before rebuilding, and you can check if the symbol is still present by checking the library with the following command:
```
nm librpc.a | grep pthread_cond
```
This command should not return pthread_cond_clockwait when building with clang 8.

**Comment by RafaGuil** [comment]
Hi, I rebuilded the airsim with clang-11 (Unreal Engine doesn'work with clang-8) and the pthread_cond_clockwait symbol doesn't appear any more:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/33eae278-a5b9-428d-a8e7-4197c6c2441a)
Then, I went to Unreal Engine, I packaged for Linux and it still doesn't work. It's a different error (a very big error), but it doesn't work:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/a157581a-74cd-45b6-b10b-b11d34f5e71d)

**Comment by wouter-heerwegh** [comment]
It seems to complain about standard symbols. Unreal engine is building with clang v11, but the rpclib can still be built with clang 8. Make sure you have the following packages installed for your clang version:
```
clang-12 clang++-12 libc++-12-dev libc++abi-12-dev
```

**Comment by RafaGuil** [comment]
Hi @wouter-heerwegh 

I was investiganting and I realized that I was using the wrong `librpc.a` (the one from ros_bridge) that is the reason for the error. Now I am using the correct one and the error persist, but it is because of `pthread_cond_clockwait`. How can I remove `pthread_cond_clockwait`? I tried to eliminate it but I couldn't do it.
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/02be24ef-6e66-469a-ba49-1fe7d33f53ab)

**Comment by RafaGuil** [comment]
Nup, it doesn't work:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/0516f886-3b73-4c41-b6c4-e071da52577f)

**Comment by wouter-heerwegh** [comment]
Looking at the prompt above, it seems that the build script did not finish completely successful.
The script should show
```
==================================================================
 AirSim libraries are built and installed.
==================================================================
```

**Comment by RafaGuil** [comment]
I'll try to reinstall the entire repository. It seems that there are some files that I was able to delete by mistake, it is inexplicable that it works for you and it doesn't work for me, having everything the same. I will tell you tomorrow.

**Comment by RafaGuil** [comment]
Hi @wouter-heerwegh,

I reinstalled the repo and also I changed to WSL Ubuntu 18.04 like you say in software install instructions. I run setup.sh and now it is building CMake, but it's taking too long. Is it normal? It's the first time that setup.sh takes me this long.

**Comment by wouter-heerwegh** [comment]
You could manually install cmake, using the apt repository. Otherwise it will build cmake from scratch, which might take some time.

**Comment by RafaGuil** [comment]
Build.sh failed again...
[building.txt](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/files/15307336/building.txt)

**Comment by wouter-heerwegh** [comment]
Not sure why the script is failing here, because the clean.sh file is definitely present in the repo

**Comment by RafaGuil** [comment]
Clean.sh is related to Unreal Engine, maybe should I install Unreal Engine for Ubuntu? Or somehow import the Windows Unreal Engine to WSL?

**Comment by wouter-heerwegh** [comment]
No, you don't need to install Unreal Engine. 

I think I know what is going on. On Windows it will append lines in a file with `^M` (see [this post](https://stackoverflow.com/questions/64749/m-character-at-end-of-lines)). Linux can not handle these characters. Can you run `git checkout . -- UE4Project/clean.sh`? This should reset the file to the original one.

It is possible that some extension in vscode or another IDE is changing these end of line characters.

**Comment by RafaGuil** [comment]
One fewer problem :), I was doing dos2unix on setup.sh and build.sh, but I didn't know that I have to do it with clean.sh too...
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/e7257743-ec9b-40b0-8972-2db0def7ddee)

...but Unreal Engine doesn't work:
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/b1cdba4b-f17e-41fa-93f5-6cf057985dff)

**Comment by wouter-heerwegh** [comment]
Does this happen when opening the unreal engine project?

If so, build AirSim for windows first, open the unreal engine project, close it, build AirSim in WSL, open the UE project and package for linux

**Comment by RafaGuil** [comment]
FINALLY!!!
![image](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/assets/80414041/72407c1c-1146-41e8-b357-8d89394d8922)

One last question, where is the settings.json file?

**Comment by wouter-heerwegh** [comment]
It is stored in the root of the repo, you should be able to just copy it into the built directory. There is still a bug I need to fix in order to fix the camera_launcher however. So unless you use camera's all should be fine.

Would you perhaps be willing to share the executable/changes to the handling? The current handling is not really amazing, so any improvement is welcome.

**Comment by RafaGuil** [comment]
Okey perfect!

This afternoon I'm gonna make a pdf with all the changes and then I will publish it right here. Thank you for everything!!!

**Comment by RafaGuil** [comment]
Here you go:
[steep_by_steep.txt](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/files/15311439/steep_by_steep.txt)

If you need anything else, tell me!

**Comment by wouter-heerwegh** [comment]
Hi @RafaGuil ,

Thanks for the quick recap of how you got it to work. You said you were making some changes on the dynamics of the car. Would you be willing to share some of the changes you made?

The car at the moment does not react all that nice imo, so any feedback is appreciated.

**Comment by RafaGuil** [comment]
Here you go! This setup could be better, but I preferred to make a realistic one.
[Dynamic data.txt](https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator/files/15338580/Dynamic.data.txt)

**Comment by wouter-heerwegh** [comment]
Thanks @RafaGuil, I'll try them out
